[Fixed] Workaround for undefined reference to `__pthread_normal_mutex_initializer_np` due to the relocation issue
Relocation Fix in binutils, Blocked for upstream
due to dependency on Eukarpov patch

Signed-off-by: Radek Bartoň <radek.barton@microsoft.com>
Signed-off-by: Thirumalai Nagalingam <thirumalai.nagalingam@multicorewareinc.com>