Cygwin: cygcheck: fix a new warning with gcc 16
The mingW-targetted gcc available in Fedora is now gcc 16.

> ../../../../../winsup/utils/mingw/cygcheck.cc: In function 'void dump_sysinfo()':
> ../../../../../winsup/utils/mingw/cygcheck.cc:1716:11: error: variable 'count_path_items' set but not used [-Werror=unused-but-set-variable=]

As far as I can tell, the value of count_path_items we compute has never
been used.

Signed-off-by: Jon Turney <jon.turney@dronecode.org.uk>