Workaround for undefined reference to `__pthread_normal_mutex_initializer_np` due to the relocation issue
Signed-off-by: Radek Bartoň <radek.barton@microsoft.com>
Signed-off-by: Thirumalai Nagalingam <thirumalai.nagalingam@multicorewareinc.com>